// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBidAsBINfWtwR2a20E-1CLG2lDJkzrV6E',
    appId: '1:814229260441:web:59de3f376a088d1b119008',
    messagingSenderId: '814229260441',
    projectId: 'voiceofislam-57e4c',
    authDomain: 'voiceofislam-57e4c.firebaseapp.com',
    storageBucket: 'voiceofislam-57e4c.appspot.com',
    measurementId: 'G-529QYNWXE1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBgqBcoU7bc3nHZVS_yRHrXzyoPOvTmjUU',
    appId: '1:814229260441:android:6fb995e952eebb6a119008',
    messagingSenderId: '814229260441',
    projectId: 'voiceofislam-57e4c',
    storageBucket: 'voiceofislam-57e4c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDamNLv07c8M2NLC8G-6eE4S-Srf7XhVVo',
    appId: '1:814229260441:ios:a58d6583ddbfeb06119008',
    messagingSenderId: '814229260441',
    projectId: 'voiceofislam-57e4c',
    storageBucket: 'voiceofislam-57e4c.appspot.com',
    iosBundleId: 'com.example.voiceofislam',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDamNLv07c8M2NLC8G-6eE4S-Srf7XhVVo',
    appId: '1:814229260441:ios:a58d6583ddbfeb06119008',
    messagingSenderId: '814229260441',
    projectId: 'voiceofislam-57e4c',
    storageBucket: 'voiceofislam-57e4c.appspot.com',
    iosBundleId: 'com.example.voiceofislam',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBidAsBINfWtwR2a20E-1CLG2lDJkzrV6E',
    appId: '1:814229260441:web:77720aa3ff57af51119008',
    messagingSenderId: '814229260441',
    projectId: 'voiceofislam-57e4c',
    authDomain: 'voiceofislam-57e4c.firebaseapp.com',
    storageBucket: 'voiceofislam-57e4c.appspot.com',
    measurementId: 'G-YJ38R2HMJS',
  );
}
